############################
## CHANGE THESE
############################

baseURL: "https://QuantumNaty.github.io/test2"
title: test2

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
